-- Normalizes guest nationality/issuer country codes for existing guest_records rows
-- using the same built-in country list and aliases used by the app/SEF integration.

create extension if not exists unaccent;

create table if not exists public.guest_country_code_map (
  lookup_key text primary key,
  country_code text not null
);

truncate table public.guest_country_code_map;

insert into public.guest_country_code_map (lookup_key, country_code)
values
  ('AFEGANISTAO', 'AFG'),
  ('AFG', 'AFG'),
  ('AFRICA DO SUL', 'ZAF'),
  ('AFRICA SUL', 'ZAF'),
  ('AGO', 'AGO'),
  ('ALB', 'ALB'),
  ('ALBANIA', 'ALB'),
  ('ALEMANHA', 'D'),
  ('AND', 'AND'),
  ('ANDORRA', 'AND'),
  ('ANGOLA', 'AGO'),
  ('ANTIGUA E BARBUDA', 'ATG'),
  ('ARABIA SAUDITA', 'SAU'),
  ('ARE', 'ARE'),
  ('ARG', 'ARG'),
  ('ARGELIA', 'DZA'),
  ('ARGENTINA', 'ARG'),
  ('ARM', 'ARM'),
  ('ARMENIA', 'ARM'),
  ('ATG', 'ATG'),
  ('AUS', 'AUS'),
  ('AUSTRALIA', 'AUS'),
  ('AUSTRIA', 'AUT'),
  ('AUT', 'AUT'),
  ('AZE', 'AZE'),
  ('AZERBAIJAO', 'AZE'),
  ('AZERBEIJAO', 'AZE'),
  ('BAHAMAS', 'BHS'),
  ('BANGLADESH', 'BGD'),
  ('BARBADOS', 'BRB'),
  ('BAREM', 'BHR'),
  ('BDI', 'BDI'),
  ('BEL', 'BEL'),
  ('BELGICA', 'BEL'),
  ('BELIZE', 'BLZ'),
  ('BEN', 'BEN'),
  ('BENIM', 'BEN'),
  ('BERMUDAS', 'BMU'),
  ('BFA', 'BFA'),
  ('BGD', 'BGD'),
  ('BGR', 'BGR'),
  ('BHR', 'BHR'),
  ('BHS', 'BHS'),
  ('BIELORRUSSIA', 'BLR'),
  ('BIELORUSSIA', 'BLR'),
  ('BIH', 'BIH'),
  ('BLR', 'BLR'),
  ('BLZ', 'BLZ'),
  ('BMU', 'BMU'),
  ('BOL', 'BOL'),
  ('BOLIVIA', 'BOL'),
  ('BOSNIA HERZEGOVINA', 'BIH'),
  ('BOTSWANA', 'BWA'),
  ('BRA', 'BRA'),
  ('BRASIL', 'BRA'),
  ('BRB', 'BRB'),
  ('BRN', 'BRN'),
  ('BRUNEI DARUSSALAM', 'BRN'),
  ('BTN', 'BTN'),
  ('BULGARIA', 'BGR'),
  ('BURKINA FASO', 'BFA'),
  ('BURUNDI', 'BDI'),
  ('BUTAO', 'BTN'),
  ('BWA', 'BWA'),
  ('CABO VERDE', 'CPV'),
  ('CAF', 'CAF'),
  ('CAMAROES', 'CMR'),
  ('CAMBOJA', 'KHM'),
  ('CAN', 'CAN'),
  ('CANADA', 'CAN'),
  ('CATAR', 'QAT'),
  ('CAZAQUISTAO', 'KAZ'),
  ('CHADE', 'TCD'),
  ('CHE', 'CHE'),
  ('CHILE', 'CHL'),
  ('CHINA', 'CHN'),
  ('CHIPRE', 'CYP'),
  ('CHL', 'CHL'),
  ('CHN', 'CHN'),
  ('CIV', 'CIV'),
  ('CMR', 'CMR'),
  ('COD', 'COD'),
  ('COG', 'COG'),
  ('COK', 'COK'),
  ('COL', 'COL'),
  ('COLOMBIA', 'COL'),
  ('COM', 'COM'),
  ('COMORES', 'COM'),
  ('CONGO', 'COG'),
  ('COREIA', 'PRK'),
  ('COREIA DO NORTE', 'PRK'),
  ('COREIA DO SUL', 'KOR'),
  ('COREIA NORTE', 'PRK'),
  ('COSTA DO MARFIM', 'CIV'),
  ('COSTA RICA', 'CRI'),
  ('CPV', 'CPV'),
  ('CRI', 'CRI'),
  ('CROACIA', 'HRV'),
  ('CUB', 'CUB'),
  ('CUBA', 'CUB'),
  ('CYP', 'CYP'),
  ('CZE', 'CZE'),
  ('D', 'D'),
  ('DINAMARCA', 'DNK'),
  ('DJI', 'DJI'),
  ('DMA', 'DMA'),
  ('DNK', 'DNK'),
  ('DOM', 'DOM'),
  ('DOMINICA', 'DMA'),
  ('DZA', 'DZA'),
  ('E U AMERICA', 'USA'),
  ('ECU', 'ECU'),
  ('EGIPTO', 'EGY'),
  ('EGY', 'EGY'),
  ('EL SALVADOR', 'SLV'),
  ('EMIRATOS ARABES UNIDOS', 'ARE'),
  ('EQUADOR', 'ECU'),
  ('ERI', 'ERI'),
  ('ERITREIA', 'ERI'),
  ('ESLOVACA', 'SVK'),
  ('ESLOVENIA', 'SVN'),
  ('ESP', 'ESP'),
  ('ESPANHA', 'ESP'),
  ('EST', 'EST'),
  ('ESTADOS UNIDOS DA AMERICA', 'USA'),
  ('ESTONIA', 'EST'),
  ('ETH', 'ETH'),
  ('ETIOPIA', 'ETH'),
  ('FILIPINAS', 'PHL'),
  ('FIN', 'FIN'),
  ('FINLANDIA', 'FIN'),
  ('FJI', 'FJI'),
  ('FRA', 'FRA'),
  ('FRANCA', 'FRA'),
  ('FSM', 'FSM'),
  ('GAB', 'GAB'),
  ('GABAO', 'GAB'),
  ('GAMBIA', 'GMB'),
  ('GANA', 'GHA'),
  ('GBR', 'GBR'),
  ('GEO', 'GEO'),
  ('GEORGIA', 'GEO'),
  ('GHA', 'GHA'),
  ('GIN', 'GIN'),
  ('GMB', 'GMB'),
  ('GNB', 'GNB'),
  ('GNQ', 'GNQ'),
  ('GRANADA', 'GRD'),
  ('GRC', 'GRC'),
  ('GRD', 'GRD'),
  ('GRECIA', 'GRC'),
  ('GTM', 'GTM'),
  ('GUAM', 'GUM'),
  ('GUATEMALA', 'GTM'),
  ('GUIANA', 'GUY'),
  ('GUINE', 'GIN'),
  ('GUINE BISSAU', 'GNB'),
  ('GUINE CONACRI', 'GIN'),
  ('GUINE EQUATORIAL', 'GNQ'),
  ('GUM', 'GUM'),
  ('GUY', 'GUY'),
  ('HAITI', 'HTI'),
  ('HKG', 'HKG'),
  ('HND', 'HND'),
  ('HOLANDA', 'NLD'),
  ('HONDURAS', 'HND'),
  ('HONG KONG', 'HKG'),
  ('HRV', 'HRV'),
  ('HTI', 'HTI'),
  ('HUN', 'HUN'),
  ('HUNGRIA', 'HUN'),
  ('IDN', 'IDN'),
  ('IEMEN', 'YEM'),
  ('ILHAS COOK', 'COK'),
  ('ILHAS FIJI', 'FJI'),
  ('ILHAS MARSHALL', 'MHL'),
  ('ILHAS MAURICIAS', 'MUS'),
  ('ILHAS SALOMAO', 'SLB'),
  ('IND', 'IND'),
  ('INDIA', 'IND'),
  ('INDONESIA', 'IDN'),
  ('IRAO', 'IRN'),
  ('IRAO REPUBLICA ISLAMICA', 'IRN'),
  ('IRAQUE', 'IRQ'),
  ('IRL', 'IRL'),
  ('IRLANDA', 'IRL'),
  ('IRN', 'IRN'),
  ('IRQ', 'IRQ'),
  ('ISL', 'ISL'),
  ('ISLANDIA', 'ISL'),
  ('ISR', 'ISR'),
  ('ISRAEL', 'ISR'),
  ('ITA', 'ITA'),
  ('ITALIA', 'ITA'),
  ('JAM', 'JAM'),
  ('JAMAICA', 'JAM'),
  ('JAPAO', 'JPN'),
  ('JIBUTI', 'DJI'),
  ('JOR', 'JOR'),
  ('JORDANIA', 'JOR'),
  ('JPN', 'JPN'),
  ('KAZ', 'KAZ'),
  ('KEN', 'KEN'),
  ('KGZ', 'KGZ'),
  ('KHM', 'KHM'),
  ('KIR', 'KIR'),
  ('KIRIBATI', 'KIR'),
  ('KNA', 'KNA'),
  ('KOR', 'KOR'),
  ('KOSOVO', 'RKS'),
  ('KOSOVO REPUBLICA DO', 'RKS'),
  ('KUWAIT', 'KWT'),
  ('KWT', 'KWT'),
  ('LAO', 'LAO'),
  ('LAOS', 'LAO'),
  ('LAOS REPUBLICA POPULAR DEMOCRATICA', 'LAO'),
  ('LBN', 'LBN'),
  ('LBR', 'LBR'),
  ('LBY', 'LBY'),
  ('LCA', 'LCA'),
  ('LESOTO', 'LSO'),
  ('LETONIA', 'LVA'),
  ('LIBANO', 'LBN'),
  ('LIBERIA', 'LBR'),
  ('LIBIA', 'LBY'),
  ('LIE', 'LIE'),
  ('LIECHTENSTEIN', 'LIE'),
  ('LITUANIA', 'LTU'),
  ('LKA', 'LKA'),
  ('LSO', 'LSO'),
  ('LTU', 'LTU'),
  ('LUX', 'LUX'),
  ('LUXEMBURGO', 'LUX'),
  ('LVA', 'LVA'),
  ('MAC', 'MAC'),
  ('MACAU', 'MAC'),
  ('MACEDONIA', 'MKD'),
  ('MACEDONIA DO NORTE', 'MKD'),
  ('MADAGASCAR', 'MDG'),
  ('MALASIA', 'MYS'),
  ('MALAWI', 'MWI'),
  ('MALDIVAS', 'MDV'),
  ('MALI', 'MLI'),
  ('MALTA', 'MLT'),
  ('MAR', 'MAR'),
  ('MARROCOS', 'MAR'),
  ('MAURICIAS', 'MUS'),
  ('MAURITANIA', 'MRT'),
  ('MAYOTTE', 'MYT'),
  ('MCO', 'MCO'),
  ('MDA', 'MDA'),
  ('MDG', 'MDG'),
  ('MDV', 'MDV'),
  ('MEX', 'MEX'),
  ('MEXICO', 'MEX'),
  ('MHL', 'MHL'),
  ('MICRONESIA', 'FSM'),
  ('MICRONESIA ESTADOS FEDERADOS DA', 'FSM'),
  ('MKD', 'MKD'),
  ('MLI', 'MLI'),
  ('MLT', 'MLT'),
  ('MMR', 'MMR'),
  ('MNE', 'MNE'),
  ('MNG', 'MNG'),
  ('MOCAMBIQUE', 'MOZ'),
  ('MOLDAVIA', 'MDA'),
  ('MONACO', 'MCO'),
  ('MONGOLIA', 'MNG'),
  ('MONSERRATE', 'MSR'),
  ('MONTENEGRO', 'MNE'),
  ('MONTENEGRO REPUBLICA DE', 'MNE'),
  ('MOZ', 'MOZ'),
  ('MRT', 'MRT'),
  ('MSR', 'MSR'),
  ('MUS', 'MUS'),
  ('MWI', 'MWI'),
  ('MYANMAR', 'MMR'),
  ('MYANMAR BIRMANIA', 'MMR'),
  ('MYS', 'MYS'),
  ('MYT', 'MYT'),
  ('NAM', 'NAM'),
  ('NAMIBIA', 'NAM'),
  ('NAURU', 'NRU'),
  ('NCL', 'NCL'),
  ('NEPAL', 'NPL'),
  ('NER', 'NER'),
  ('NGA', 'NGA'),
  ('NIC', 'NIC'),
  ('NICARAGUA', 'NIC'),
  ('NIGER', 'NER'),
  ('NIGERIA', 'NGA'),
  ('NIU', 'NIU'),
  ('NIUE', 'NIU'),
  ('NLD', 'NLD'),
  ('NOR', 'NOR'),
  ('NORUEGA', 'NOR'),
  ('NOVA CALEDONIA', 'NCL'),
  ('NOVA ZELANDIA', 'NZL'),
  ('NPL', 'NPL'),
  ('NRU', 'NRU'),
  ('NZL', 'NZL'),
  ('OMAN', 'OMN'),
  ('OMN', 'OMN'),
  ('PAISES BAIXOS', 'NLD'),
  ('PAK', 'PAK'),
  ('PALAU', 'PLW'),
  ('PALESTINA', 'PSE'),
  ('PAN', 'PAN'),
  ('PANAMA', 'PAN'),
  ('PAPUASIA NOVA GUINE', 'PNG'),
  ('PAQUISTAO', 'PAK'),
  ('PARAGUAI', 'PRY'),
  ('PER', 'PER'),
  ('PERU', 'PER'),
  ('PHL', 'PHL'),
  ('PLW', 'PLW'),
  ('PNG', 'PNG'),
  ('POL', 'POL'),
  ('POLONIA', 'POL'),
  ('PORTO RICO', 'PRI'),
  ('PORTUGAL', 'PRT'),
  ('PRI', 'PRI'),
  ('PRK', 'PRK'),
  ('PRT', 'PRT'),
  ('PRY', 'PRY'),
  ('PSE', 'PSE'),
  ('PTR', 'PRT'),
  ('QAT', 'QAT'),
  ('QUATAR', 'QAT'),
  ('QUENIA', 'KEN'),
  ('QUIRGUIZISTAO', 'KGZ'),
  ('REINO UNIDO', 'GBR'),
  ('REP CENTRO AFRICANA', 'CAF'),
  ('REP DEMOC CONGO ZAIRE', 'COD'),
  ('REP DEMOCRATICA CONGO', 'COD'),
  ('REPUBLICA ARABE DO IEMEN', 'YEM'),
  ('REPUBLICA AZERBAIJAO', 'AZE'),
  ('REPUBLICA BIELORRUSSIA', 'BLR'),
  ('REPUBLICA CENTRO AFRICANA', 'CAF'),
  ('REPUBLICA CHECA', 'CZE'),
  ('REPUBLICA DA COREIA', 'KOR'),
  ('REPUBLICA DA MACEDONIA DO NORTE', 'MKD'),
  ('REPUBLICA DO CAZAQUISTAO', 'KAZ'),
  ('REPUBLICA DO SUDAO DO SUL', 'SSD'),
  ('REPUBLICA DOMINICANA', 'DOM'),
  ('REPUBLICA ESLOVACA', 'SVK'),
  ('REPUBLICA MOLDAVIA', 'MDA'),
  ('REPUBLICA UCRANIA', 'UKR'),
  ('REU', 'REU'),
  ('REUNIAO', 'REU'),
  ('RKS', 'RKS'),
  ('ROMENIA', 'ROU'),
  ('ROU', 'ROU'),
  ('RUANDA', 'RWA'),
  ('RUS', 'RUS'),
  ('RUSSIA', 'RUS'),
  ('RUSSIA FEDERACAO', 'RUS'),
  ('RWA', 'RWA'),
  ('SAMOA', 'WSM'),
  ('SANTA LUCIA', 'LCA'),
  ('SANTA SE', 'VAT'),
  ('SANTA SE CIDADE ESTADO DO VATICANO', 'VAT'),
  ('SAO CRISTOVAO E NEVIS', 'KNA'),
  ('SAO MARINO', 'SMR'),
  ('SAO TOME PRINCIPE', 'STP'),
  ('SAO VICENTE E GRANADINAS', 'VCT'),
  ('SAO VICENTE E GRENADINAS', 'VCT'),
  ('SAU', 'SAU'),
  ('SDN', 'SDN'),
  ('SEN', 'SEN'),
  ('SENEGAL', 'SEN'),
  ('SERRA LEOA', 'SLE'),
  ('SERVIA', 'SRB'),
  ('SERVIA REPUBLICA DA', 'SRB'),
  ('SEYCHELLES', 'SYC'),
  ('SGP', 'SGP'),
  ('SINGAPURA', 'SGP'),
  ('SIRIA', 'SYR'),
  ('SIRIA REPUBLICA ARABE DA', 'SYR'),
  ('SLB', 'SLB'),
  ('SLE', 'SLE'),
  ('SLV', 'SLV'),
  ('SMR', 'SMR'),
  ('SOM', 'SOM'),
  ('SOMALIA', 'SOM'),
  ('SRB', 'SRB'),
  ('SRI LANCA', 'LKA'),
  ('SRI LANKA', 'LKA'),
  ('SSD', 'SSD'),
  ('STP', 'STP'),
  ('SUAZILANDIA', 'SWZ'),
  ('SUDAO', 'SDN'),
  ('SUDAO DO SUL', 'SSD'),
  ('SUECIA', 'SWE'),
  ('SUICA', 'CHE'),
  ('SUR', 'SUR'),
  ('SURINAME', 'SUR'),
  ('SVK', 'SVK'),
  ('SVN', 'SVN'),
  ('SWE', 'SWE'),
  ('SWZ', 'SWZ'),
  ('SYC', 'SYC'),
  ('SYR', 'SYR'),
  ('TAILANDA', 'THA'),
  ('TAILANDIA', 'THA'),
  ('TAIWAN', 'TWN'),
  ('TAJIQUISTAO', 'TJK'),
  ('TANZANIA', 'TZA'),
  ('TANZANIA REPUBLICA DA', 'TZA'),
  ('TCD', 'TCD'),
  ('TGO', 'TGO'),
  ('THA', 'THA'),
  ('TIMOR LESTE', 'TLS'),
  ('TJK', 'TJK'),
  ('TKM', 'TKM'),
  ('TLS', 'TLS'),
  ('TOGO', 'TGO'),
  ('TON', 'TON'),
  ('TONGA', 'TON'),
  ('TRINDADE E TOBAGO', 'TTO'),
  ('TTO', 'TTO'),
  ('TUN', 'TUN'),
  ('TUNISIA', 'TUN'),
  ('TUR', 'TUR'),
  ('TURQUEMENISTAO', 'TKM'),
  ('TURQUIA', 'TUR'),
  ('TUV', 'TUV'),
  ('TUVALU', 'TUV'),
  ('TWN', 'TWN'),
  ('TZA', 'TZA'),
  ('UCRANIA', 'UKR'),
  ('UGA', 'UGA'),
  ('UGANDA', 'UGA'),
  ('UKR', 'UKR'),
  ('UNIAO DAS COMORES', 'COM'),
  ('URUGUAI', 'URY'),
  ('URY', 'URY'),
  ('USA', 'USA'),
  ('USBEQUISTAO', 'UZB'),
  ('UZB', 'UZB'),
  ('VANUATU', 'VUT'),
  ('VAT', 'VAT'),
  ('VCT', 'VCT'),
  ('VEN', 'VEN'),
  ('VENEZUELA', 'VEN'),
  ('VIETNAME', 'VNM'),
  ('VNM', 'VNM'),
  ('VUT', 'VUT'),
  ('WSM', 'WSM'),
  ('YEM', 'YEM'),
  ('ZAF', 'ZAF'),
  ('ZAMBIA', 'ZMB'),
  ('ZIMBABWE', 'ZWE'),
  ('ZMB', 'ZMB'),
  ('ZWE', 'ZWE');

create or replace function public.guest_country_fix_text(p_value text)
returns text
language plpgsql
immutable
as $$
declare
  raw_value text := btrim(coalesce(p_value, ''), E' \t\n\r"');
  repaired_value text := raw_value;
begin
  begin
    repaired_value := convert_from(convert_to(raw_value, 'LATIN1'), 'UTF8');
  exception
    when others then
      repaired_value := raw_value;
  end;
  if repaired_value is not null and repaired_value <> '' then
    return repaired_value;
  end if;
  return raw_value;
end;
$$;

create or replace function public.guest_country_lookup_key(p_value text)
returns text
language sql
immutable
as $$
  select nullif(
    upper(
      regexp_replace(
        trim(unaccent(public.guest_country_fix_text(coalesce(p_value, '')))),
        '[^A-Z0-9]+',
        ' ',
        'g'
      )
    ),
    ''
  );
$$;

create or replace function public.guest_country_resolve_code(p_value text)
returns text
language sql
stable
as $$
  select coalesce((
    select m.country_code
    from public.guest_country_code_map m
    where m.lookup_key = public.guest_country_lookup_key(p_value)
  ), '');
$$;

update public.guest_records
set nationality_code = public.guest_country_resolve_code(nationality)
where coalesce(trim(nationality_code), '') = ''
  and coalesce(trim(nationality), '') <> '';

update public.guest_records
set issuer_country_code = public.guest_country_resolve_code(issuer_country)
where coalesce(trim(issuer_country_code), '') = ''
  and coalesce(trim(issuer_country), '') <> '';

create or replace function public.guests_bi_nationality_key(p_nationality text, p_nationality_code text)
returns text
language sql
immutable
as $$
  select coalesce(
    nullif(upper(trim(coalesce(p_nationality_code, ''))), ''),
    public.guest_country_resolve_code(p_nationality),
    public.guest_country_lookup_key(p_nationality),
    'UNKNOWN'
  );
$$;
