-- Canonicalizes guest nationality and issuer_country text from their stored country codes
-- using the SEF/XML reference Designacao values supplied by the user.

create table if not exists public.guest_country_name_map (
  country_code text primary key,
  country_name text not null
);

truncate table public.guest_country_name_map;

insert into public.guest_country_name_map (country_code, country_name)
values
  ('AFG', 'Afeganistão'),
  ('AGO', 'Angola'),
  ('ALB', 'Albânia'),
  ('AND', 'Andorra'),
  ('ARE', 'Emiratos Árabes Unidos'),
  ('ARG', 'Argentina'),
  ('ARM', 'Arménia'),
  ('ATG', 'Antígua e Barbuda'),
  ('AUS', 'Austrália'),
  ('AUT', 'Áustria'),
  ('AZE', 'República Azerbaijão'),
  ('BDI', 'Burundi'),
  ('BEL', 'Bélgica'),
  ('BEN', 'Benim'),
  ('BFA', 'Burkina Faso'),
  ('BGD', 'Bangladesh'),
  ('BGR', 'Bulgaria'),
  ('BHR', 'Barém'),
  ('BHS', 'Bahamas'),
  ('BIH', 'Bósnia Herzegovina'),
  ('BLR', 'República Bielorrússia'),
  ('BLZ', 'Belize'),
  ('BMU', 'Bermudas'),
  ('BOL', 'Bolívia'),
  ('BRA', 'Brasil'),
  ('BRB', 'Barbados'),
  ('BRN', 'Brunei Darussalam'),
  ('BTN', 'Butão'),
  ('BWA', 'Botswana'),
  ('CAF', 'República Centro Africana'),
  ('CAN', 'Canadá'),
  ('CHE', 'Suíça'),
  ('CHL', 'Chile'),
  ('CHN', 'China'),
  ('CIV', 'Costa do Marfim'),
  ('CMR', 'Camarões'),
  ('COD', 'Rep. Democ. Congo (Zaire)'),
  ('COG', 'Congo'),
  ('COK', 'Ilhas Cook'),
  ('COL', 'Colômbia'),
  ('COM', 'União das Comores'),
  ('CPV', 'Cabo Verde'),
  ('CRI', 'Costa Rica'),
  ('CUB', 'Cuba'),
  ('CYP', 'Chipre'),
  ('CZE', 'República Checa'),
  ('D', 'Alemanha'),
  ('DJI', 'Jibuti'),
  ('DMA', 'Dominica'),
  ('DNK', 'Dinamarca'),
  ('DOM', 'República Dominicana'),
  ('DZA', 'Argélia'),
  ('ECU', 'Equador'),
  ('EGY', 'Egipto'),
  ('ERI', 'Eritreia'),
  ('ESP', 'Espanha'),
  ('EST', 'Estónia'),
  ('ETH', 'Etiópia'),
  ('FIN', 'Finlândia'),
  ('FJI', 'Ilhas Fiji'),
  ('FRA', 'França'),
  ('FSM', 'Micronésia, Estados Federados da'),
  ('GAB', 'Gabão'),
  ('GBR', 'Reino Unido'),
  ('GEO', 'Geórgia'),
  ('GHA', 'Gana'),
  ('GIN', 'Guiné Conacri'),
  ('GMB', 'Gâmbia'),
  ('GNB', 'Guiné-Bissau'),
  ('GNQ', 'Guiné Equatorial'),
  ('GRC', 'Grécia'),
  ('GRD', 'Granada'),
  ('GTM', 'Guatemala'),
  ('GUM', 'Guam'),
  ('GUY', 'Guiana'),
  ('HKG', 'Hong-Kong'),
  ('HND', 'Honduras'),
  ('HRV', 'Croácia'),
  ('HTI', 'Haiti'),
  ('HUN', 'Hungria'),
  ('IDN', 'Indonésia'),
  ('IND', 'Índia'),
  ('IRL', 'Irlanda'),
  ('IRN', 'Irão, República Islâmica'),
  ('IRQ', 'Iraque'),
  ('ISL', 'Islândia'),
  ('ISR', 'Israel'),
  ('ITA', 'Itália'),
  ('JAM', 'Jamaica'),
  ('JOR', 'Jordânia'),
  ('JPN', 'Japão'),
  ('KAZ', 'República do Cazaquistão'),
  ('KEN', 'Quénia'),
  ('KGZ', 'Quirguizistão'),
  ('KHM', 'Camboja'),
  ('KIR', 'Kiribati'),
  ('KNA', 'São Cristóvão e Nevis'),
  ('KOR', 'República da Coreia'),
  ('KWT', 'Kuwait'),
  ('LAO', 'Laos, República Popular Democrática'),
  ('LBN', 'Líbano'),
  ('LBR', 'Libéria'),
  ('LBY', 'Líbia'),
  ('LCA', 'Santa Lúcia'),
  ('LIE', 'Liechtenstein'),
  ('LKA', 'Sri Lanka'),
  ('LSO', 'Lesoto'),
  ('LTU', 'Lituânia'),
  ('LUX', 'Luxemburgo'),
  ('LVA', 'Letónia'),
  ('MAC', 'Macau'),
  ('MAR', 'Marrocos'),
  ('MCO', 'Mónaco'),
  ('MDA', 'República Moldávia'),
  ('MDG', 'Madagáscar'),
  ('MDV', 'Maldivas'),
  ('MEX', 'México'),
  ('MHL', 'Ilhas Marshall'),
  ('MKD', 'República da Macedónia do Norte'),
  ('MLI', 'Mali'),
  ('MLT', 'Malta'),
  ('MMR', 'Myanmar (Birmânia)'),
  ('MNE', 'Montenegro, República de'),
  ('MNG', 'Mongólia'),
  ('MOZ', 'Moçambique'),
  ('MRT', 'Mauritânia'),
  ('MSR', 'Monserrate'),
  ('MUS', 'Ilhas Maurícias'),
  ('MWI', 'Malawi'),
  ('MYS', 'Malásia'),
  ('MYT', 'Mayotte'),
  ('NAM', 'Namíbia'),
  ('NCL', 'Nova Caledónia'),
  ('NER', 'Níger'),
  ('NGA', 'Nigéria'),
  ('NIC', 'Nicarágua'),
  ('NIU', 'Niue'),
  ('NLD', 'Países Baixos'),
  ('NOR', 'Noruega'),
  ('NPL', 'Nepal'),
  ('NRU', 'Nauru'),
  ('NZL', 'Nova Zelândia'),
  ('OMN', 'Oman'),
  ('PAK', 'Paquistão'),
  ('PAN', 'Panamá'),
  ('PER', 'Peru'),
  ('PHL', 'Filipinas'),
  ('PLW', 'PALAU'),
  ('PNG', 'Papuásia Nova Guiné'),
  ('POL', 'Polónia'),
  ('PRI', 'Porto Rico'),
  ('PRK', 'Coreia'),
  ('PRT', 'Portugal'),
  ('PRY', 'Paraguai'),
  ('PSE', 'Palestina'),
  ('QAT', 'Quatar'),
  ('REU', 'Reunião'),
  ('RKS', 'Kosovo, República do'),
  ('ROU', 'Roménia'),
  ('RUS', 'Rússia, Federação'),
  ('RWA', 'Ruanda'),
  ('SAU', 'Arábia Saudita'),
  ('SDN', 'Sudão'),
  ('SEN', 'Senegal'),
  ('SGP', 'Singapura'),
  ('SLB', 'Ilhas Salomão'),
  ('SLE', 'Serra Leoa'),
  ('SLV', 'El Salvador'),
  ('SMR', 'São Marino'),
  ('SOM', 'Somália'),
  ('SRB', 'Sérvia, República da'),
  ('SSD', 'República do Sudão do Sul'),
  ('STP', 'São Tomé Príncipe'),
  ('SUR', 'Suriname'),
  ('SVK', 'República Eslovaca'),
  ('SVN', 'Eslovénia'),
  ('SWE', 'Suécia'),
  ('SWZ', 'Suazilândia'),
  ('SYC', 'Seychelles'),
  ('SYR', 'Síria, República Árabe da'),
  ('TCD', 'Chade'),
  ('TGO', 'Togo'),
  ('THA', 'Tailândia'),
  ('TJK', 'Tajiquistão'),
  ('TKM', 'Turquemenistão'),
  ('TLS', 'Timor-Leste'),
  ('TON', 'Tonga'),
  ('TTO', 'Trindade e Tobago'),
  ('TUN', 'Tunísia'),
  ('TUR', 'Turquia'),
  ('TUV', 'Tuvalu'),
  ('TWN', 'Taiwan'),
  ('TZA', 'Tanzânia, República da'),
  ('UGA', 'Uganda'),
  ('UKR', 'República Ucrânia'),
  ('URY', 'Uruguai'),
  ('USA', 'Estados Unidos da América'),
  ('UZB', 'Usbequistão'),
  ('VAT', 'Santa Sé (Cidade Estado do Vaticano)'),
  ('VCT', 'São Vicente e Grenadinas'),
  ('VEN', 'Venezuela'),
  ('VNM', 'Vietname'),
  ('VUT', 'Vanuatu'),
  ('WSM', 'Samoa'),
  ('YEM', 'Republica Árabe do Iémen'),
  ('ZAF', 'África do Sul'),
  ('ZMB', 'Zâmbia'),
  ('ZWE', 'Zimbabwe');

create or replace function public.guest_country_canonical_code(p_code text)
returns text
language sql
immutable
as $$
  select case upper(trim(coalesce(p_code, '')))
    when '' then ''
    when 'PTR' then 'PRT'
    else upper(trim(coalesce(p_code, '')) )
  end;
$$;

create or replace function public.guest_country_designacao(p_code text)
returns text
language sql
stable
as $$
  select coalesce((
    select m.country_name
    from public.guest_country_name_map m
    where m.country_code = public.guest_country_canonical_code(p_code)
  ), '');
$$;

update public.guest_records
set nationality = public.guest_country_designacao(nationality_code)
where coalesce(trim(nationality_code), '') <> ''
  and public.guest_country_designacao(nationality_code) <> ''
  and coalesce(nationality, '') <> public.guest_country_designacao(nationality_code);

update public.guest_records
set issuer_country = public.guest_country_designacao(issuer_country_code)
where coalesce(trim(issuer_country_code), '') <> ''
  and public.guest_country_designacao(issuer_country_code) <> ''
  and coalesce(issuer_country, '') <> public.guest_country_designacao(issuer_country_code);
