-- Normalizes guest nationality/issuer country codes for existing guest_records rows
-- that still have blank nationality_code and/or issuer_country_code.
-- Uses the same built-in SEF/app country list supplied by the user.

create extension if not exists unaccent;

create table if not exists public.guest_country_code_map (
  lookup_key text primary key,
  country_code text not null
);

truncate table public.guest_country_code_map;

insert into public.guest_country_code_map (lookup_key, country_code)
values
  ('ADOS UNIDOS DA AMERICA', 'USA'),
  ('AFEGANIST O', 'AFG'),
  ('AFG', 'AFG'),
  ('AFRICA DO SUL', 'ZAF'),
  ('AFRICA SUL', 'ZAF'),
  ('AGO', 'AGO'),
  ('ALB', 'ALB'),
  ('ALB NIA', 'ALB'),
  ('ALEMANHA', 'D'),
  ('AND', 'AND'),
  ('ANDORRA', 'AND'),
  ('ANGOLA', 'AGO'),
  ('ANT GUA E BARBUDA', 'ATG'),
  ('AR BIA SAUDITA', 'SAU'),
  ('ARABIA SAUDITA', 'SAU'),
  ('ARE', 'ARE'),
  ('ARG', 'ARG'),
  ('ARG LIA', 'DZA'),
  ('ARGELIA', 'DZA'),
  ('ARGENTINA', 'ARG'),
  ('ARM', 'ARM'),
  ('ARM NIA', 'ARM'),
  ('ATG', 'ATG'),
  ('AUS', 'AUS'),
  ('AUSTR LIA', 'AUS'),
  ('AUT', 'AUT'),
  ('AZE', 'AZE'),
  ('AZERBAIJ O', 'AZE'),
  ('AZERBEIJAO', 'AZE'),
  ('B LGICA', 'BEL'),
  ('B SNIA HERZEGOVINA', 'BIH'),
  ('BAHAMAS', 'BHS'),
  ('BANGLADESH', 'BGD'),
  ('BAR M', 'BHR'),
  ('BARBADOS', 'BRB'),
  ('BAREM', 'BHR'),
  ('BDI', 'BDI'),
  ('BEL', 'BEL'),
  ('BELARUS', 'BLR'),
  ('BELIZE', 'BLZ'),
  ('BEN', 'BEN'),
  ('BENIM', 'BEN'),
  ('BERMUDAS', 'BMU'),
  ('BFA', 'BFA'),
  ('BGD', 'BGD'),
  ('BGR', 'BGR'),
  ('BHR', 'BHR'),
  ('BHS', 'BHS'),
  ('BIELOR SSIA', 'BLR'),
  ('BIELORRUSSIA', 'BLR'),
  ('BIH', 'BIH'),
  ('BLR', 'BLR'),
  ('BLZ', 'BLZ'),
  ('BMU', 'BMU'),
  ('BOL', 'BOL'),
  ('BOL VIA', 'BOL'),
  ('BOSNIA', 'BIH'),
  ('BOSNIA HERZEGOVINA', 'BIH'),
  ('BOTSWANA', 'BWA'),
  ('BRA', 'BRA'),
  ('BRASIL', 'BRA'),
  ('BRAZIL', 'BRA'),
  ('BRB', 'BRB'),
  ('BRN', 'BRN'),
  ('BRUNEI', 'BRN'),
  ('BRUNEI DARUSSALAM', 'BRN'),
  ('BTN', 'BTN'),
  ('BULG RIA', 'BGR'),
  ('BULGARIA', 'BGR'),
  ('BURKINA FASO', 'BFA'),
  ('BURUNDI', 'BDI'),
  ('BUT O', 'BTN'),
  ('BWA', 'BWA'),
  ('CABO VERDE', 'CPV'),
  ('CAF', 'CAF'),
  ('CAMAR ES', 'CMR'),
  ('CAMAROES', 'CMR'),
  ('CAMBOJA', 'KHM'),
  ('CAN', 'CAN'),
  ('CANAD', 'CAN'),
  ('CATAR', 'QAT'),
  ('CAZAQUIST O', 'KAZ'),
  ('CHADE', 'TCD'),
  ('CHE', 'CHE'),
  ('CHILE', 'CHL'),
  ('CHINA', 'CHN'),
  ('CHIPRE', 'CYP'),
  ('CHL', 'CHL'),
  ('CHN', 'CHN'),
  ('CISKEI', 'ZAF'),
  ('CIV', 'CIV'),
  ('CMR', 'CMR'),
  ('COD', 'COD'),
  ('COG', 'COG'),
  ('COK', 'COK'),
  ('COL', 'COL'),
  ('COL MBIA', 'COL'),
  ('COLOMBIA', 'COL'),
  ('COM', 'COM'),
  ('COMORES', 'COM'),
  ('CONGO', 'COG'),
  ('COREIA', 'PRK'),
  ('COREIA DO NORTE', 'PRK'),
  ('COREIA DO SUL', 'KOR'),
  ('COREIA NORTE', 'PRK'),
  ('COSTA DO MARFIM', 'CIV'),
  ('COSTA RICA', 'CRI'),
  ('CPV', 'CPV'),
  ('CRI', 'CRI'),
  ('CRO CIA', 'HRV'),
  ('CROACIA', 'HRV'),
  ('CUB', 'CUB'),
  ('CUBA', 'CUB'),
  ('CYP', 'CYP'),
  ('CZE', 'CZE'),
  ('D', 'D'),
  ('DINAMARCA', 'DNK'),
  ('DJI', 'DJI'),
  ('DMA', 'DMA'),
  ('DNK', 'DNK'),
  ('DOM', 'DOM'),
  ('DOMINICA', 'DMA'),
  ('DZA', 'DZA'),
  ('E U AM RICA', 'USA'),
  ('ECU', 'ECU'),
  ('EGIPTO', 'EGY'),
  ('EGY', 'EGY'),
  ('EL SALVADOR', 'SLV'),
  ('EMIRATOS ARABES', 'ARE'),
  ('EMIRATOS ARABES UNIDOS', 'ARE'),
  ('EMIRATOS RABES UNIDOS', 'ARE'),
  ('EQUADOR', 'ECU'),
  ('ERI', 'ERI'),
  ('ERITREIA', 'ERI'),
  ('ESLOV NIA', 'SVN'),
  ('ESLOVACA', 'SVK'),
  ('ESLOVAQUIA', 'SVK'),
  ('ESP', 'ESP'),
  ('ESPANHA', 'ESP'),
  ('EST', 'EST'),
  ('EST NIA', 'EST'),
  ('ESTADOS UNIDOS DA AM RICA', 'USA'),
  ('ESTONIA', 'EST'),
  ('ETH', 'ETH'),
  ('ETI PIA', 'ETH'),
  ('FILIPINAS', 'PHL'),
  ('FIN', 'FIN'),
  ('FINL NDIA', 'FIN'),
  ('FINLANDIA', 'FIN'),
  ('FJI', 'FJI'),
  ('FRA', 'FRA'),
  ('FRAN A', 'FRA'),
  ('FRANCE', 'FRA'),
  ('FRICA DO SUL', 'ZAF'),
  ('FSM', 'FSM'),
  ('G MBIA', 'GMB'),
  ('GAB', 'GAB'),
  ('GAB O', 'GAB'),
  ('GANA', 'GHA'),
  ('GBR', 'GBR'),
  ('GE RGIA', 'GEO'),
  ('GEO', 'GEO'),
  ('GERMANY', 'D'),
  ('GHA', 'GHA'),
  ('GIN', 'GIN'),
  ('GMB', 'GMB'),
  ('GNB', 'GNB'),
  ('GNQ', 'GNQ'),
  ('GR CIA', 'GRC'),
  ('GRA BRETANHA', 'GBR'),
  ('GRANADA', 'GRD'),
  ('GRC', 'GRC'),
  ('GRD', 'GRD'),
  ('GRECIA', 'GRC'),
  ('GTM', 'GTM'),
  ('GUAM', 'GUM'),
  ('GUATEMALA', 'GTM'),
  ('GUIANA', 'GUY'),
  ('GUIN', 'GIN'),
  ('GUIN BISSAU', 'GNB'),
  ('GUIN CONACRI', 'GIN'),
  ('GUIN EQUATORIAL', 'GNQ'),
  ('GUM', 'GUM'),
  ('GUY', 'GUY'),
  ('HAITI', 'HTI'),
  ('HKG', 'HKG'),
  ('HND', 'HND'),
  ('HOLANDA', 'NLD'),
  ('HONDURAS', 'HND'),
  ('HONG KONG', 'HKG'),
  ('HONGKONG', 'HKG'),
  ('HRV', 'HRV'),
  ('HTI', 'HTI'),
  ('HUN', 'HUN'),
  ('HUNGRIA', 'HUN'),
  ('I MEN', 'YEM'),
  ('IDN', 'IDN'),
  ('ILHAS COOK', 'COK'),
  ('ILHAS FIJI', 'FJI'),
  ('ILHAS MARSHALL', 'MHL'),
  ('ILHAS MAUR CIAS', 'MUS'),
  ('ILHAS MAURICIAS', 'MUS'),
  ('ILHAS SALOM O', 'SLB'),
  ('IND', 'IND'),
  ('INDON SIA', 'IDN'),
  ('IR O', 'IRN'),
  ('IR O REP BLICA ISL MICA', 'IRN'),
  ('IRAO', 'IRN'),
  ('IRAQUE', 'IRQ'),
  ('IRL', 'IRL'),
  ('IRLANDA', 'IRL'),
  ('IRN', 'IRN'),
  ('IRQ', 'IRQ'),
  ('ISL', 'ISL'),
  ('ISL NDIA', 'ISL'),
  ('ISLANDIA', 'ISL'),
  ('ISR', 'ISR'),
  ('ISRAEL', 'ISR'),
  ('IT LIA', 'ITA'),
  ('ITA', 'ITA'),
  ('ITALY', 'ITA'),
  ('JAM', 'JAM'),
  ('JAMAICA', 'JAM'),
  ('JAP O', 'JPN'),
  ('JIBUTI', 'DJI'),
  ('JOR', 'JOR'),
  ('JORD NIA', 'JOR'),
  ('JORDANIA', 'JOR'),
  ('JPN', 'JPN'),
  ('JUGOSLAVIA', 'YUG'),
  ('KAMPUCHEA', 'KHM'),
  ('KAZ', 'KAZ'),
  ('KAZAKHSTAN', 'KAZ'),
  ('KEN', 'KEN'),
  ('KGZ', 'KGZ'),
  ('KHM', 'KHM'),
  ('KIR', 'KIR'),
  ('KIRIBATI', 'KIR'),
  ('KNA', 'KNA'),
  ('KOR', 'KOR'),
  ('KOSOVO', 'RKS'),
  ('KOSOVO REP BLICA DO', 'RKS'),
  ('KUWAIT', 'KWT'),
  ('KWAIT', 'KWT'),
  ('KWT', 'KWT'),
  ('L BANO', 'LBN'),
  ('L BIA', 'LBY'),
  ('LAO', 'LAO'),
  ('LAOS', 'LAO'),
  ('LAOS REP BLICA POPULAR DEMOCR TICA', 'LAO'),
  ('LATVIA', 'LVA'),
  ('LBN', 'LBN'),
  ('LBR', 'LBR'),
  ('LBY', 'LBY'),
  ('LCA', 'LCA'),
  ('LESOTO', 'LSO'),
  ('LET NIA', 'LVA'),
  ('LIB RIA', 'LBR'),
  ('LIE', 'LIE'),
  ('LIECHTENSTEIN', 'LIE'),
  ('LITU NIA', 'LTU'),
  ('LITUANIA', 'LTU'),
  ('LKA', 'LKA'),
  ('LSO', 'LSO'),
  ('LTU', 'LTU'),
  ('LUX', 'LUX'),
  ('LUXEMBURGO', 'LUX'),
  ('LVA', 'LVA'),
  ('M NACO', 'MCO'),
  ('M XICO', 'MEX'),
  ('MAC', 'MAC'),
  ('MACAU', 'MAC'),
  ('MACED NIA DO NORTE', 'MKD'),
  ('MACEDONIA', 'MKD'),
  ('MADAG SCAR', 'MDG'),
  ('MAL SIA', 'MYS'),
  ('MALASIA', 'MYS'),
  ('MALAWI', 'MWI'),
  ('MALDIVAS', 'MDV'),
  ('MALI', 'MLI'),
  ('MALTA', 'MLT'),
  ('MAR', 'MAR'),
  ('MARROCOS', 'MAR'),
  ('MAUR CIAS', 'MUS'),
  ('MAURICIA', 'MUS'),
  ('MAURIT NIA', 'MRT'),
  ('MAYOTTE', 'MYT'),
  ('MCO', 'MCO'),
  ('MDA', 'MDA'),
  ('MDG', 'MDG'),
  ('MDV', 'MDV'),
  ('MEX', 'MEX'),
  ('MHL', 'MHL'),
  ('MICRON SIA', 'FSM'),
  ('MICRON SIA ESTADOS FEDERADOS DA', 'FSM'),
  ('MKD', 'MKD'),
  ('MLI', 'MLI'),
  ('MLT', 'MLT'),
  ('MMR', 'MMR'),
  ('MNE', 'MNE'),
  ('MNG', 'MNG'),
  ('MO AMBIQUE', 'MOZ'),
  ('MOLD VIA', 'MDA'),
  ('MONG LIA', 'MNG'),
  ('MONSERRATE', 'MSR'),
  ('MONTENEGRO', 'MNE'),
  ('MONTENEGRO REP BLICA DE', 'MNE'),
  ('MOZ', 'MOZ'),
  ('MRT', 'MRT'),
  ('MSR', 'MSR'),
  ('MUS', 'MUS'),
  ('MWI', 'MWI'),
  ('MYANMAR', 'MMR'),
  ('MYANMAR BIRM NIA', 'MMR'),
  ('MYS', 'MYS'),
  ('MYT', 'MYT'),
  ('N GER', 'NER'),
  ('NAM', 'NAM'),
  ('NAM BIA', 'NAM'),
  ('NAURU', 'NRU'),
  ('NCL', 'NCL'),
  ('NDIA', 'IND'),
  ('NEPAL', 'NPL'),
  ('NER', 'NER'),
  ('NGA', 'NGA'),
  ('NIC', 'NIC'),
  ('NICAR GUA', 'NIC'),
  ('NIG RIA', 'NGA'),
  ('NIU', 'NIU'),
  ('NIUE', 'NIU'),
  ('NLD', 'NLD'),
  ('NOR', 'NOR'),
  ('NORUEGA', 'NOR'),
  ('NOVA CALED NIA', 'NCL'),
  ('NOVA ZEL NDIA', 'NZL'),
  ('NPL', 'NPL'),
  ('NRU', 'NRU'),
  ('NZL', 'NZL'),
  ('OMAN', 'OMN'),
  ('OMN', 'OMN'),
  ('PA SES BAIXOS', 'NLD'),
  ('PAK', 'PAK'),
  ('PALAU', 'PLW'),
  ('PALESTINA', 'PSE'),
  ('PAN', 'PAN'),
  ('PANAM', 'PAN'),
  ('PAPU SIA NOVA GUIN', 'PNG'),
  ('PAQUIST O', 'PAK'),
  ('PARAGUAI', 'PRY'),
  ('PER', 'PER'),
  ('PERU', 'PER'),
  ('PHL', 'PHL'),
  ('PLW', 'PLW'),
  ('PNG', 'PNG'),
  ('POL', 'POL'),
  ('POL NIA', 'POL'),
  ('POLAND', 'POL'),
  ('POLONIA', 'POL'),
  ('PORTO RICO', 'PRI'),
  ('PORTUGAL', 'PRT'),
  ('PORTUGUESE', 'PRT'),
  ('PRI', 'PRI'),
  ('PRK', 'PRK'),
  ('PRT', 'PRT'),
  ('PRY', 'PRY'),
  ('PSE', 'PSE'),
  ('PTR', 'PRT'),
  ('QAT', 'QAT'),
  ('QATAR', 'QAT'),
  ('QU NIA', 'KEN'),
  ('QUATAR', 'QAT'),
  ('QUIRGUIZIST O', 'KGZ'),
  ('R SSIA', 'RUS'),
  ('R SSIA FEDERA O', 'RUS'),
  ('REINO UNIDO', 'GBR'),
  ('REP BLICA AZERBAIJ O', 'AZE'),
  ('REP BLICA BIELORR SSIA', 'BLR'),
  ('REP BLICA CENTRO AFRICANA', 'CAF'),
  ('REP BLICA CHECA', 'CZE'),
  ('REP BLICA DA COREIA', 'KOR'),
  ('REP BLICA DA MACED NIA DO NORTE', 'MKD'),
  ('REP BLICA DO CAZAQUIST O', 'KAZ'),
  ('REP BLICA DO SUD O DO SUL', 'SSD'),
  ('REP BLICA DOMINICANA', 'DOM'),
  ('REP BLICA ESLOVACA', 'SVK'),
  ('REP BLICA MOLD VIA', 'MDA'),
  ('REP BLICA UCR NIA', 'UKR'),
  ('REP CENTRO AFRICANA', 'CAF'),
  ('REP DEMOC CONGO ZAIRE', 'COD'),
  ('REP DEMOCR TICA CONGO', 'COD'),
  ('REP DOMINICANA', 'DOM'),
  ('REP SAO DOMINGOS', 'DOM'),
  ('REPUBLICA BIELORRUSSIA', 'BLR'),
  ('REPUBLICA CHECA', 'CZE'),
  ('REPUBLICA DO CASAQUISTAO', 'KAZ'),
  ('REPUBLICA DOMINICANA', 'DOM'),
  ('REPUBLICA RABE DO I MEN', 'YEM'),
  ('REU', 'REU'),
  ('REUNI O', 'REU'),
  ('RKS', 'RKS'),
  ('ROM NIA', 'ROU'),
  ('ROMENIA', 'ROU'),
  ('ROU', 'ROU'),
  ('RUANDA', 'RWA'),
  ('RUS', 'RUS'),
  ('RWA', 'RWA'),
  ('S O CRIST V O E NEVIS', 'KNA'),
  ('S O MARINO', 'SMR'),
  ('S O TOM PR NCIPE', 'STP'),
  ('S O VICENTE E GRANADINAS', 'VCT'),
  ('S O VICENTE E GRENADINAS', 'VCT'),
  ('S RIA', 'SYR'),
  ('S RIA REP BLICA RABE DA', 'SYR'),
  ('S RVIA', 'SRB'),
  ('S RVIA REP BLICA DA', 'SRB'),
  ('SAMOA', 'WSM'),
  ('SANTA L CIA', 'LCA'),
  ('SANTA S', 'VAT'),
  ('SANTA S CIDADE ESTADO DO VATICANO', 'VAT'),
  ('SAO TOME E PRINCIPE', 'STP'),
  ('SAO TOME PRINCIPE', 'STP'),
  ('SAU', 'SAU'),
  ('SDN', 'SDN'),
  ('SEN', 'SEN'),
  ('SENEGAL', 'SEN'),
  ('SERRA LEOA', 'SLE'),
  ('SEYCHELLES', 'SYC'),
  ('SGP', 'SGP'),
  ('SINGAPURA', 'SGP'),
  ('SLB', 'SLB'),
  ('SLE', 'SLE'),
  ('SLV', 'SLV'),
  ('SMR', 'SMR'),
  ('SOM', 'SOM'),
  ('SOM LIA', 'SOM'),
  ('SRB', 'SRB'),
  ('SRI LANCA', 'LKA'),
  ('SRI LANKA', 'LKA'),
  ('SSD', 'SSD'),
  ('STP', 'STP'),
  ('SU A', 'CHE'),
  ('SU CIA', 'SWE'),
  ('SUAZIL NDIA', 'SWZ'),
  ('SUD O', 'SDN'),
  ('SUD O DO SUL', 'SSD'),
  ('SUDAO SUL', 'SSD'),
  ('SUECIA', 'SWE'),
  ('SUR', 'SUR'),
  ('SURINAME', 'SUR'),
  ('SVK', 'SVK'),
  ('SVN', 'SVN'),
  ('SWE', 'SWE'),
  ('SWZ', 'SWZ'),
  ('SYC', 'SYC'),
  ('SYR', 'SYR'),
  ('TAIL NDIA', 'THA'),
  ('TAILANDA', 'THA'),
  ('TAIWAN', 'TWN'),
  ('TAJIQUIST O', 'TJK'),
  ('TAJIQUISTAOO', 'TJK'),
  ('TANZ NIA', 'TZA'),
  ('TANZ NIA REP BLICA DA', 'TZA'),
  ('TCD', 'TCD'),
  ('TGO', 'TGO'),
  ('THA', 'THA'),
  ('TIMOR LESTE', 'TLS'),
  ('TJK', 'TJK'),
  ('TKM', 'TKM'),
  ('TLS', 'TLS'),
  ('TOGO', 'TGO'),
  ('TON', 'TON'),
  ('TONGA', 'TON'),
  ('TRINDADE E TOBAGO', 'TTO'),
  ('TTO', 'TTO'),
  ('TUN', 'TUN'),
  ('TUN SIA', 'TUN'),
  ('TUR', 'TUR'),
  ('TURKEY', 'TUR'),
  ('TURQUEMENIST O', 'TKM'),
  ('TURQUIA', 'TUR'),
  ('TUV', 'TUV'),
  ('TUVALU', 'TUV'),
  ('TWN', 'TWN'),
  ('TZA', 'TZA'),
  ('UCRANIA', 'UKR'),
  ('UGA', 'UGA'),
  ('UGANDA', 'UGA'),
  ('UK BRITISH CITIZEN', 'GBR'),
  ('UKR', 'UKR'),
  ('UNI O DAS COMORES', 'COM'),
  ('URUGUAI', 'URY'),
  ('URY', 'URY'),
  ('USA', 'USA'),
  ('USBEQUIST O', 'UZB'),
  ('USBEQUISTAO', 'UZB'),
  ('USTRIA', 'AUT'),
  ('UZB', 'UZB'),
  ('VANUATU', 'VUT'),
  ('VAT', 'VAT'),
  ('VCT', 'VCT'),
  ('VEN', 'VEN'),
  ('VENEZUELA', 'VEN'),
  ('VIETNAME', 'VNM'),
  ('VNM', 'VNM'),
  ('VUT', 'VUT'),
  ('WSM', 'WSM'),
  ('YEM', 'YEM'),
  ('Z MBIA', 'ZMB'),
  ('ZAF', 'ZAF'),
  ('ZAMBIA', 'ZMB'),
  ('ZIMBABWE', 'ZWE'),
  ('ZMB', 'ZMB'),
  ('ZWE', 'ZWE');

-- Extra aliases from unresolved issuer-country values, still resolved into
-- the same SEF/app country-code universe.
insert into public.guest_country_code_map (lookup_key, country_code)
values
  ('ALEMENTHA', 'D'),
  ('ALEMNHA', 'D'),
  ('ALEMANHA', 'D'),
  ('ALGERIA', 'DZA'),
  ('AUSTRALIA', 'AUS'),
  ('AUSTRALIAN', 'AUS'),
  ('AUTRALIA', 'AUS'),
  ('ASUTRALIA', 'AUS'),
  ('AUSTRLIA', 'AUS'),
  ('AUSTRIALIA', 'AUS'),
  ('AUST', 'AUS'),
  ('AUSTRIA', 'AUT'),
  ('BELG', 'BEL'),
  ('BELGIUM', 'BEL'),
  ('BLEGICA', 'BEL'),
  ('BOSNIA HERZEGOVINA', 'BIH'),
  ('BRA', 'BRA'),
  ('BRASIL', 'BRA'),
  ('BRASILEIRA', 'BRA'),
  ('BRASIK', 'BRA'),
  ('BRAZIL', 'BRA'),
  ('CANADA', 'CAN'),
  ('CN', 'CHN'),
  ('CNADA', 'CAN'),
  ('COREA DO SUL', 'KOR'),
  ('COREAI DO SUL', 'KOR'),
  ('COSTA DO MARFIM', 'CIV'),
  ('CZECH', 'CZE'),
  ('CZECH REPUBLIC', 'CZE'),
  ('DEUTSCH', 'D'),
  ('DEUTSCHAND', 'D'),
  ('DEUTSCHLAND', 'D'),
  ('DEUTLAND', 'D'),
  ('DEUTSH', 'D'),
  ('DENMARK', 'DNK'),
  ('EGYPT', 'EGY'),
  ('ENGLAND', 'GBR'),
  ('ESPANA', 'ESP'),
  ('ESTADOS UNIDOS', 'USA'),
  ('EUA', 'USA'),
  ('FINLAND', 'FIN'),
  ('FINLANDIA', 'FIN'),
  ('FRANCA', 'FRA'),
  ('FRANCESA', 'FRA'),
  ('GBR', 'GBR'),
  ('GER', 'D'),
  ('GERMANY', 'D'),
  ('GREECE', 'GRC'),
  ('GRECIA', 'GRC'),
  ('HOLLAND', 'NLD'),
  ('HOLANDESA', 'NLD'),
  ('INDIA', 'IND'),
  ('INGLATERRA', 'GBR'),
  ('IRLANDE', 'IRL'),
  ('IRELAND', 'IRL'),
  ('ITALIA', 'ITA'),
  ('ITALY', 'ITA'),
  ('JAPAN', 'JPN'),
  ('JAPAO', 'JPN'),
  ('KAZHAQUISTAN', 'KAZ'),
  ('KOREA', 'KOR'),
  ('KOREIA', 'KOR'),
  ('LATIVIA', 'LVA'),
  ('LATVIA', 'LVA'),
  ('LITHUANIA', 'LTU'),
  ('NED', 'NLD'),
  ('NEDERLAND', 'NLD'),
  ('NEDERLANDEN', 'NLD'),
  ('NEDERLANSE', 'NLD'),
  ('NETHERLAND', 'NLD'),
  ('NETHERLANDS', 'NLD'),
  ('NEW ZEALAND', 'NZL'),
  ('NEW ZELAND', 'NZL'),
  ('NOVA ZELANDIA', 'NZL'),
  ('NORWAY', 'NOR'),
  ('PAISES BAIXOS', 'NLD'),
  ('PHILIPPINES', 'PHL'),
  ('POLAND', 'POL'),
  ('POLONIA', 'POL'),
  ('POR', 'PRT'),
  ('PORT', 'PRT'),
  ('PORTUGUESA', 'PRT'),
  ('PT', 'PRT'),
  ('PRT', 'PRT'),
  ('REBUBLICA SLOVENIA', 'SVN'),
  ('REP CHECA', 'CZE'),
  ('REP COREIA', 'KOR'),
  ('REPUBLIC OF KOREA', 'KOR'),
  ('REPUBLICA DA COREIA', 'KOR'),
  ('REPUBLICA CHECA', 'CZE'),
  ('REPUBLICA ESLOVENA', 'SVN'),
  ('REPUBLICA SERVIA', 'SRB'),
  ('ROMAMIA', 'ROU'),
  ('ROMANIA', 'ROU'),
  ('RUSSIA', 'RUS'),
  ('SINGAPORE', 'SGP'),
  ('SINGAPURE', 'SGP'),
  ('SLOVAKIA', 'SVK'),
  ('SLOVENIA', 'SVN'),
  ('SOUTH AFRICA', 'ZAF'),
  ('SOUTH KOREA', 'KOR'),
  ('SPAIN', 'ESP'),
  ('SUECIA', 'SWE'),
  ('SUICA', 'CHE'),
  ('SUISSE', 'CHE'),
  ('SWEDEN', 'SWE'),
  ('SWISS', 'CHE'),
  ('SWITZERLAND', 'CHE'),
  ('TAILANDIA', 'THA'),
  ('THAILANDIA', 'THA'),
  ('TANZANIA', 'TZA'),
  ('TURKEY', 'TUR'),
  ('U K', 'GBR'),
  ('U K IRELAND', 'GBR'),
  ('UK', 'GBR'),
  ('UK BRITISH CITIZEN', 'GBR'),
  ('UK IRELAND', 'GBR'),
  ('US A', 'USA'),
  ('USA', 'USA')
on conflict (lookup_key) do update
set country_code = excluded.country_code;

-- Canonical country-name aliases. These mirror the actual country names
-- users typed in guest history and avoid relying on malformed mojibake keys.
insert into public.guest_country_code_map (lookup_key, country_code)
values
  ('AFEGANISTAO', 'AFG'),
  ('ALBANIA', 'ALB'),
  ('ALEMANHA', 'D'),
  ('ANDORRA', 'AND'),
  ('ANGOLA', 'AGO'),
  ('ANTIGUA E BARBUDA', 'ATG'),
  ('ARABIA SAUDITA', 'SAU'),
  ('ARGELIA', 'DZA'),
  ('ARGENTINA', 'ARG'),
  ('ARMENIA', 'ARM'),
  ('AUSTRALIA', 'AUS'),
  ('AUSTRIA', 'AUT'),
  ('AZERBEIJAO', 'AZE'),
  ('BAHAMAS', 'BHS'),
  ('BANGLADESH', 'BGD'),
  ('BAREM', 'BHR'),
  ('BARBADOS', 'BRB'),
  ('BELARUS', 'BLR'),
  ('BELGICA', 'BEL'),
  ('BELIZE', 'BLZ'),
  ('BENIM', 'BEN'),
  ('BERMUDAS', 'BMU'),
  ('BIELORRUSSIA', 'BLR'),
  ('BOLIVIA', 'BOL'),
  ('BOSNIA', 'BIH'),
  ('BOSNIA HERZEGOVINA', 'BIH'),
  ('BOTSWANA', 'BWA'),
  ('BRASIL', 'BRA'),
  ('BRUNEI', 'BRN'),
  ('BULGARIA', 'BGR'),
  ('BURUNDI', 'BDI'),
  ('BUTAO', 'BTN'),
  ('CABO VERDE', 'CPV'),
  ('CAMAROES', 'CMR'),
  ('CAMBOJA', 'KHM'),
  ('CANADA', 'CAN'),
  ('CAZAQUISTAO', 'KAZ'),
  ('CHADE', 'TCD'),
  ('CHILE', 'CHL'),
  ('CHINA', 'CHN'),
  ('CHIPRE', 'CYP'),
  ('CISKEI', 'ZAF'),
  ('COLOMBIA', 'COL'),
  ('COMORES', 'COM'),
  ('CONGO', 'COG'),
  ('COREIA', 'KOR'),
  ('COREIA DO SUL', 'KOR'),
  ('COSTA DO MARFIM', 'CIV'),
  ('COSTA RICA', 'CRI'),
  ('CROACIA', 'HRV'),
  ('CUBA', 'CUB'),
  ('DINAMARCA', 'DNK'),
  ('DOMINICA', 'DMA'),
  ('EGIPTO', 'EGY'),
  ('EL SALVADOR', 'SLV'),
  ('EMIRATOS ARABES', 'ARE'),
  ('EMIRATOS ARABES UNIDOS', 'ARE'),
  ('EQUADOR', 'ECU'),
  ('ERITREIA', 'ERI'),
  ('ESLOVACA', 'SVK'),
  ('ESLOVAQUIA', 'SVK'),
  ('ESLOVENIA', 'SVN'),
  ('ESPANHA', 'ESP'),
  ('ESTADOS UNIDOS', 'USA'),
  ('ESTADOS UNIDOS DA AMERICA', 'USA'),
  ('ESTONIA', 'EST'),
  ('ETIOPIA', 'ETH'),
  ('EUA', 'USA'),
  ('FILIPINAS', 'PHL'),
  ('FINLANDIA', 'FIN'),
  ('FRANCA', 'FRA'),
  ('GABAO', 'GAB'),
  ('GAMBIA', 'GMB'),
  ('GANA', 'GHA'),
  ('GEORGIA', 'GEO'),
  ('GRA BRETANHA', 'GBR'),
  ('GRANADA', 'GRD'),
  ('GRECIA', 'GRC'),
  ('GUATEMALA', 'GTM'),
  ('GUINE BISSAU', 'GNB'),
  ('GUINE CONACRI', 'GIN'),
  ('GUIANA', 'GUY'),
  ('HAITI', 'HTI'),
  ('HOLANDA', 'NLD'),
  ('HONDURAS', 'HND'),
  ('HONG KONG', 'HKG'),
  ('HUNGRIA', 'HUN'),
  ('IEMEN', 'YEM'),
  ('INDIA', 'IND'),
  ('INDONESIA', 'IDN'),
  ('IRAO', 'IRN'),
  ('IRAQUE', 'IRQ'),
  ('IRLANDA', 'IRL'),
  ('ISLANDIA', 'ISL'),
  ('ISRAEL', 'ISR'),
  ('ITALIA', 'ITA'),
  ('JAMAICA', 'JAM'),
  ('JAPAO', 'JPN'),
  ('JORDANIA', 'JOR'),
  ('JUGOSLAVIA', 'YUG'),
  ('KAMPUCHEA', 'KHM'),
  ('KAZAKHSTAN', 'KAZ'),
  ('KOREA', 'KOR'),
  ('KUWAIT', 'KWT'),
  ('KWAIT', 'KWT'),
  ('LAOS', 'LAO'),
  ('LATVIA', 'LVA'),
  ('LIBANO', 'LBN'),
  ('LIBIA', 'LBY'),
  ('LIECHTENSTEIN', 'LIE'),
  ('LITUANIA', 'LTU'),
  ('LUXEMBURGO', 'LUX'),
  ('MACAU', 'MAC'),
  ('MACEDONIA', 'MKD'),
  ('MADAGASCAR', 'MDG'),
  ('MALASIA', 'MYS'),
  ('MALI', 'MLI'),
  ('MALTA', 'MLT'),
  ('MARROCOS', 'MAR'),
  ('MAURICIA', 'MUS'),
  ('MAURITANIA', 'MRT'),
  ('MEXICO', 'MEX'),
  ('MOLDAVIA', 'MDA'),
  ('MONACO', 'MCO'),
  ('MONGOLIA', 'MNG'),
  ('MONTENEGRO', 'MNE'),
  ('MOCAMBIQUE', 'MOZ'),
  ('MYANMAR', 'MMR'),
  ('NAMIBIA', 'NAM'),
  ('NEPAL', 'NPL'),
  ('NIGER', 'NER'),
  ('NIGERIA', 'NGA'),
  ('NICARAGUA', 'NIC'),
  ('NORUEGA', 'NOR'),
  ('NOVA ZELANDIA', 'NZL'),
  ('OMAN', 'OMN'),
  ('PAISES BAIXOS', 'NLD'),
  ('PALESTINA', 'PSE'),
  ('PANAMA', 'PAN'),
  ('PAQUISTAO', 'PAK'),
  ('PAPUASIA NOVA GUINE', 'PNG'),
  ('PARAGUAI', 'PRY'),
  ('PERU', 'PER'),
  ('POLONIA', 'POL'),
  ('PORTUGAL', 'PRT'),
  ('PORTUGUESE', 'PRT'),
  ('QUATAR', 'QAT'),
  ('QUENIA', 'KEN'),
  ('QUIRGUIZISTAO', 'KGZ'),
  ('REINO UNIDO', 'GBR'),
  ('REP DEMOC CONGO ZAIRE', 'COD'),
  ('REP SAO DOMINGOS', 'DOM'),
  ('REPUBLICA BIELORRUSSIA', 'BLR'),
  ('REPUBLICA CHECA', 'CZE'),
  ('REPUBLICA DO CASAQUISTAO', 'KAZ'),
  ('REPUBLICA DOMINICANA', 'DOM'),
  ('REPUBLICA MOLDAVIA', 'MDA'),
  ('ROMENIA', 'ROU'),
  ('RUANDA', 'RWA'),
  ('RUSSIA', 'RUS'),
  ('SAMOA', 'WSM'),
  ('SAO MARINO', 'SMR'),
  ('SAO TOME E PRINCIPE', 'STP'),
  ('SAO TOME PRINCIPE', 'STP'),
  ('SAO VICENTE E GRENADINAS', 'VCT'),
  ('SENEGAL', 'SEN'),
  ('SERRA LEOA', 'SLE'),
  ('SERVIA', 'SRB'),
  ('SINGAPURA', 'SGP'),
  ('SIRIA', 'SYR'),
  ('SOMALIA', 'SOM'),
  ('SOUTH AFRICA', 'ZAF'),
  ('SOUTH KOREA', 'KOR'),
  ('SRI LANKA', 'LKA'),
  ('SUAZILANDIA', 'SWZ'),
  ('SUDA O', 'SDN'),
  ('SUDAO', 'SDN'),
  ('SUDAO SUL', 'SSD'),
  ('SUICA', 'CHE'),
  ('SUECIA', 'SWE'),
  ('SURINAME', 'SUR'),
  ('SWITZERLAND', 'CHE'),
  ('TAILANDA', 'THA'),
  ('TAILANDIA', 'THA'),
  ('TAIWAN', 'TWN'),
  ('TAJIQUISTAO', 'TJK'),
  ('TANZANIA', 'TZA'),
  ('TIMOR LESTE', 'TLS'),
  ('TOGO', 'TGO'),
  ('TRINDADE E TOBAGO', 'TTO'),
  ('TUNISIA', 'TUN'),
  ('TURKEY', 'TUR'),
  ('TURQUEMENISTAO', 'TKM'),
  ('TURQUIA', 'TUR'),
  ('UCRANIA', 'UKR'),
  ('UGANDA', 'UGA'),
  ('URUGUAI', 'URY'),
  ('USBEQUISTAO', 'UZB'),
  ('VANUATU', 'VUT'),
  ('VENEZUELA', 'VEN'),
  ('VIETNAME', 'VNM'),
  ('YEMEN', 'YEM'),
  ('ZAMBIA', 'ZMB'),
  ('ZIMBABWE', 'ZWE')
on conflict (lookup_key) do update
set country_code = excluded.country_code;

-- Final long-tail aliases from the remaining unresolved nationality and
-- issuer_country values after the main normalization passes.
insert into public.guest_country_code_map (lookup_key, country_code)
values
  ('AUTRIA', 'AUT'),
  ('BAN', 'BGD'),
  ('BR', 'BRA'),
  ('CG MEXICO', 'MEX'),
  ('CHI', 'CHL'),
  ('CHINA', 'CHN'),
  ('COLOMBA', 'COL'),
  ('COMBIA', 'COL'),
  ('CROATIA', 'HRV'),
  ('CZ', 'CZE'),
  ('DANMARK', 'DNK'),
  ('DEUTSLAND', 'D'),
  ('DOS UNIDOS DA AMERICA', 'USA'),
  ('ESPAHA', 'ESP'),
  ('ESPAMHA', 'ESP'),
  ('ESPANNHA', 'ESP'),
  ('FILANDIA', 'FIN'),
  ('FINLADIA', 'FIN'),
  ('FINLANIA', 'FIN'),
  ('FRANCIA', 'FRA'),
  ('GERGIA', 'GEO'),
  ('GRE', 'GRC'),
  ('GUINE', 'GIN'),
  ('HLANDA', 'NLD'),
  ('HOLANDA', 'NLD'),
  ('HUNGARY', 'HUN'),
  ('IRAN', 'IRN'),
  ('IRLAND', 'IRL'),
  ('JAP', 'JPN'),
  ('JAPAAO', 'JPN'),
  ('JAPAP', 'JPN'),
  ('JHOLANDA', 'NLD'),
  ('JNP', 'JPN'),
  ('KAZAQUISTAO', 'KAZ'),
  ('LETONIA', 'LVA'),
  ('MAL', 'MYS'),
  ('MALASYA', 'MYS'),
  ('MALAYSIA', 'MYS'),
  ('MAROCCO', 'MAR'),
  ('MYANMAR BIRMANIA', 'MMR'),
  ('N ZELAND', 'NZL'),
  ('NORUEGUESA', 'NOR'),
  ('OSTERREICH', 'AUT'),
  ('PAKISTAN', 'PAK'),
  ('REP DEMOC CONGO ZAIRE', 'COD'),
  ('REPUBLICA DA BIELORRUSSIA', 'BLR'),
  ('REPUBLICA UCRANIA', 'UKR'),
  ('REINO UNIDO E IRALNDA', 'GBR'),
  ('REINO UNIDO E IRLANDA', 'GBR'),
  ('RUSSIAN', 'RUS'),
  ('SANTA LUCIA', 'LCA'),
  ('SERBIA', 'SRB'),
  ('SWEDEN SUEDE', 'SWE'),
  ('TRINIDAD E TOBACO', 'TTO'),
  ('TRINIDAD TOBAGO', 'TTO'),
  ('U K', 'GBR'),
  ('VISEU', 'PRT'),
  ('LISBOA', 'PRT'),
  ('MADRID', 'ESP'),
  ('VALENCIA', 'ESP'),
  ('LONDRES', 'GBR'),
  ('NOVA IORQUE', 'USA'),
  ('QUEBEC', 'CAN'),
  ('MARKT SCHWABEN', 'D'),
  ('VILLINGEN SCHWENNINGEN', 'D')
on conflict (lookup_key) do update
set country_code = excluded.country_code;

create or replace function public.guest_country_fix_text(p_value text)
returns text
language plpgsql
immutable
as $$
declare
  raw_value text := btrim(coalesce(p_value, ''), E' \t\n\r"');
  repaired_value text := raw_value;
begin
  begin
    repaired_value := convert_from(convert_to(raw_value, 'LATIN1'), 'UTF8');
  exception when others then
    repaired_value := raw_value;
  end;
  return coalesce(nullif(repaired_value, ''), raw_value);
end;
$$;

create or replace function public.guest_country_lookup_key(p_value text)
returns text
language sql
immutable
as $$
  select nullif(
    regexp_replace(
      upper(trim(unaccent(public.guest_country_fix_text(coalesce(p_value, ''))))),
      '[^A-Z0-9]+',
      ' ',
      'g'
    ),
    ''
  );
$$;

create or replace function public.guest_country_resolve_code(p_value text)
returns text
language sql
stable
as $$
  select coalesce((
    select m.country_code
    from public.guest_country_code_map m
    where m.lookup_key = public.guest_country_lookup_key(p_value)
  ), '');
$$;

update public.guest_records
set nationality_code = public.guest_country_resolve_code(nationality)
where coalesce(trim(nationality_code), '') = ''
  and coalesce(trim(nationality), '') <> '';

update public.guest_records
set issuer_country_code = public.guest_country_resolve_code(issuer_country)
where coalesce(trim(issuer_country_code), '') = ''
  and coalesce(trim(issuer_country), '') <> '';

create or replace function public.guests_bi_nationality_key(p_nationality text, p_nationality_code text)
returns text
language sql
immutable
as $$
  select coalesce(
    nullif(upper(trim(coalesce(p_nationality_code, ''))), ''),
    public.guest_country_resolve_code(p_nationality),
    public.guest_country_lookup_key(p_nationality),
    'UNKNOWN'
  );
$$;
